Feature/database refactor
uzh/z-pool-tool pull request #361
Opened 2024-03-27 17:41 UTC by mabiede

2024-05-07 08:13 UTC, timohuber requested changes

2024-05-07 08:13 UTC, timohuber commented on pool/queue/queue.ml
> +(* let stop_schedule : (unit -> unit) option ref = ref None *)
Plese remove

2024-05-07 08:13 UTC, timohuber commented on pool/queue/queue.ml
> +let register ?(kind = Service) ?(jobs = []) () =
Is the kind `Worker` in use?

2024-05-07 14:31 UTC, mabiede commented on pool/app/pool_user/pool_user.ml
> +    let* (_ : t) = Repo_password.find label user_id in
Check for the user's existence (which includes not "inactive"). As for "define", it's unnecessary to provide the old password.

2024-05-07 15:26 UTC, mabiede commented on pool/cqrs_command/contact_command.ml
>    include Common.CommandSig
yes, done.

2024-05-07 16:35 UTC, mabiede commented on pool/app/assignment/repo/repo_entity.ml
> +  let t = make_caqti_type Caqti_type.bool (create %> CCResult.return) value
In an intermediate step, I added an entity interface file, which didn't expose the `type t`. I reset it.

2024-05-07 16:37 UTC, mabiede commented on pool/database/database.ml
> +  let test_connection () =
Yes, I was also thinking of adding a separate process to watch the connection to the root database. As it's not implemented yet, I removed it.

2024-05-07 16:41 UTC, mabiede commented on pool/database/entity.ml
> +      | Maintenance [@name "maintenance"] [@printer print "maintenance"]
The database and the tenant share the status, as they cannot exist without each other.

2024-05-07 16:51 UTC, mabiede commented on pool/database/pools.ml
> +    Hashtbl.create (max 1 Config.expected_databases)
This is to make sure the Hashtable gets initialized with a natural size. Basically, it's possible to set the "expected_databases" configuration to a negative number.

2024-05-07 16:54 UTC, mabiede commented on pool/database/service.ml
> +      (* Use PPX for backtrace *)
No, this comment belongs to the line below (intended).

2024-05-07 16:56 UTC, mabiede commented on pool/queue/queue.ml
> +let register ?(kind = Service) ?(jobs = []) () =
Yes, for the "worker" ;-)

2024-05-08 07:43 UTC, timohuber commented on pool/database/pools.ml
> +  let transactions label queries =
as discussed, lets update naming

2024-05-13 10:47 UTC, timohuber approved these changes

2024-05-13 10:52 UTC, merged