implement persistent pool queue service
uzh/z-pool-tool pull request #392
Opened 2024-07-04 21:09 UTC by mabiede

- [x] implement persistent pool queue service 
- [x] update email and text messages for the new queue
- [ ] switch "MatchesFilter" to new pool queue
- [ ] remove old queue

2024-07-22 10:07 UTC, timohuber requested changes

2024-07-25 05:45 UTC, mabiede commented on pool/app/pool_database/migrations/migration_202407171415.ml
> +    {sql| DELETE FROM core_migration_state WHERE namespace = 'queue' |sql}
Yes, the migrations aren't registered anymore, which results in a missing namespace.
As the namespace is unique and we decided to use the timestamps for migrations in future, I'd use it like this.

2024-07-25 05:46 UTC, mabiede commented on pool/app/pool_database/migrations/migration_202407171415.ml
> +        persisted_at, handled_at, last_error, last_error_at, database_label, created_at, updated_at)
fixed

2024-07-25 05:47 UTC, mabiede commented on pool/app/email/event.ml
> +type job =
this is still open, working on it - depending on the timing I'll create a follow-up issue

2024-07-25 06:26 UTC, mabiede commented on pool/app/email/event.ml
> +type job =
done

2024-07-25 10:18 UTC, timohuber requested changes

2024-07-25 10:18 UTC, timohuber commented on pool/app/text_message/event.ml
> +type job =
The naming should be updated here as well

2024-07-25 10:18 UTC, timohuber commented on pool/app/text_message/event.ml
> +let sent ?new_recipient job = Sent (job, new_recipient)
`CCPair.make` would do the same, no?

2024-07-25 11:05 UTC, mabiede commented on pool/app/pool_database/root.ml
> +      ; Migration_202402091434.migration ()
to be able to use the same migration for the root and the tenant databases

2024-07-25 11:34 UTC, timohuber approved these changes

2024-07-25 11:42 UTC, merged